package folk.sisby.starcaller.util;

import java.util.List;

public class StarNameUtil {
    public static final List<String> STAR_NAMES = List.of(
            "Gěng Hé",
            "Montuno",
            "Nǚ Xiù",
            "Helvetios",
            "Felixvarela",
            "Fuyue",
            "Bài Jiù",
            "Pherkad",
            "Xī Cì Jiàng",
            "Nushagak",
            "Zubeneschamali",
            "Markab",
            "Shàng Tái èr",
            "Huàn Zhě",
            "Mekbuda",
            "Alshain",
            "Tài Wēi Yòu Yuán",
            "Lusitânia",
            "Cè",
            "Nèi Píng",
            "Tiān Gōu",
            "Shēn Qí",
            "Wǔ Zhū Hóu",
            "Zhāo Yáo",
            "Sulafat",
            "Tiān Tián",
            "Vindemiatrix",
            "Jūn Jǐng",
            "Musica",
            "Kitalpha",
            "Albireo",
            "Lí Gōng",
            "Albaldah",
            "Xī Shǎng Jiāng",
            "Fū Zhì",
            "Lich",
            "Navi",
            "Tiān Lǐn",
            "Gar",
            "Alasia",
            "Dǒu",
            "Alsephina",
            "Tiān Zhù",
            "Acubens",
            "Liǔ Xiù",
            "Tiān Qián",
            "Hé Jiān",
            "Cervantes",
            "Tiān Bàng",
            "Shàng Fǔ",
            "Tiān Chú",
            "Tonatiuh",
            "Qí",
            "Chángshá",
            "Kāng",
            "Wurren",
            "Alkes",
            "Píng",
            "Tiān Shū",
            "Castula",
            "Qì",
            "Orkaria",
            "Léi Diàn",
            "Moriah",
            "Lucilinburhuc",
            "Zuǒ Xiá",
            "Algol",
            "Graffias",
            "Shǎo Fǔ",
            "Nǚ Shǐ",
            "Acamar",
            "Deneb",
            "Tiān Guān",
            "Subra",
            "Tiān Láo",
            "Fǔ",
            "Shàng Wèi",
            "Dùn Wán",
            "Aniara",
            "Atlas",
            "Bosona",
            "Gōu Chén",
            "Dubhe",
            "Zhōng Tái",
            "Chē Sì",
            "Xìng Chén",
            "Gacrux",
            "Zuǒ Shū",
            "Nán Mén",
            "Errai",
            "Zhé Wēi",
            "Cháng Yuán",
            "Athebyne",
            "Hunor",
            "Alpheratz",
            "Shào Wēi",
            "Tiān Xuán",
            "Koeia",
            "Chǔ",
            "Píng Dào",
            "Tǔ Sī Kōng",
            "Shàng Shū",
            "Beemim",
            "Sān Shī",
            "Běi Là Shī Mén",
            "Tiān Yuàn",
            "Wēi Xiù",
            "Shào Fǔ",
            "Mirfak",
            "Alathfar",
            "Yuè",
            "Tarf",
            "Yè Zhě",
            "Sī Fēi",
            "Tiān Qūn",
            "Zhèng",
            "Tiān Quán",
            "Xuānyuán",
            "Kalausi",
            "Shǐ",
            "Lěi Bì Zhèn",
            "Gudja",
            "Marfik",
            "Dabih",
            "Fù Lù",
            "Guàn",
            "Yed Posterior",
            "Alnair",
            "Kaus Media",
            "Alula Borealis",
            "Què Qiū",
            "Barnard's Star",
            "Dà Lǐ",
            "Zhōu yī",
            "Tiān Jī",
            "Horna",
            "Zhōu Dǐng",
            "Scheat",
            "Qín",
            "Misam",
            "Aiolos",
            "Berehynia",
            "Wú Yuè",
            "Mazaalai",
            "Bì Xiù",
            "Proxima Centauri",
            "Yù Héng",
            "Zào Fù",
            "Hán",
            "Liáng",
            "Koit",
            "Unurgunite",
            "Gǒu Guó",
            "Tureis",
            "Tiān Zūn",
            "Rotanev",
            "Wén Chāng",
            "Franz",
            "Qī Gōng",
            "Aldebaran",
            "Jiǔ Zhōu Shū Kǒu",
            "Yáo Guāng",
            "Wài Chú",
            "Saclateni",
            "Guahayona",
            "Xuán Gē",
            "Larawag",
            "Xián Chí",
            "Kosjenka",
            "Morava",
            "Rana",
            "Bharani",
            "Dofida",
            "Amadioha",
            "Algieba",
            "Intercrus",
            "Zhū Wáng",
            "Juǎn Shé",
            "Tiān Gāo",
            "Qín yī",
            "Sadachbia",
            "Wáng Liáng",
            "Chertan",
            "Tapecue",
            "Zubenelgenubi",
            "Bunda",
            "Tiaki",
            "Tè Shé",
            "Merak",
            "Gàng",
            "Haedus",
            "Jūn Mén",
            "Jī Shuǐ",
            "Zhōu",
            "Rukbat",
            "Avior",
            "Alsciaukat",
            "Xīn Xiù",
            "Tiān Jì",
            "Dōng Cì Jiàng",
            "Alnilam",
            "Citadelle",
            "Kàng Chí",
            "Niú Xiù",
            "Shǎng Fǔ",
            "Regulus",
            "Shǎng Bì",
            "Solaris",
            "Zhù Shǐ",
            "Gnomon",
            "Zuǒ Qí",
            "Shǎo Bì",
            "Tabit",
            "Wèi",
            "Gé Dào",
            "Al Minliar al Asad",
            "Hú",
            "Bā",
            "Xīng Xiù",
            "Yòu Xiá",
            "Tiān Dà Jiāng Jūn",
            "Rasalgethi",
            "Nán Hé",
            "Fumalsamakah",
            "Canopus",
            "Sceptrum",
            "Hé Gǔ",
            "Atria",
            "Tiān Rǔ",
            "Imai",
            "Veritate",
            "Láng Jiàng",
            "Tiān Qiāng",
            "Kuma",
            "Chuán Shè",
            "Cóng Guān",
            "Asellus Primus",
            "Stribor",
            "Talitha",
            "Nunki",
            "Mesarthim",
            "Mebsuta",
            "Ceibo",
            "Lù",
            "Formosa",
            "Taiyangshou",
            "Gōu Yín",
            "Zī Xiù",
            "Ginan",
            "Nǚ Chuáng",
            "Okab",
            "Xī Cì Jiāng",
            "Tiān Shì Zuó Yuán",
            "Yòu Shū",
            "Tiān Jiāng",
            "Mǎo Xiù",
            "Mönch",
            "Tiān Yīn",
            "Xú",
            "Dì Xí",
            "Tevel",
            "Iklil",
            "Tupã",
            "Fū Yuè",
            "Gǒu",
            "Lóu Xiù",
            "Libertas",
            "Almach",
            "Jī Xiù",
            "Xī Cì Xiāng",
            "Chú Hāo",
            "Tiān Fú",
            "Tiān Shì Yòu Yuán",
            "Copernicus",
            "Irena",
            "Tiān Lěi Chéng",
            "Dōng Shàng Jiàng",
            "Merga",
            "Muliphein",
            "Nèi Jiē",
            "Alzirr",
            "Yīn Dé",
            "Spica",
            "Cor Caroli",
            "Minchir",
            "Shǔi Fǔ",
            "Jiàn Bì",
            "Wezen",
            "Minelauva",
            "Dà Jiǎo",
            "Asellus Borealis",
            "Rapeto",
            "Shǔ",
            "Acrux",
            "Shào Wèi",
            "Shàng Chéng",
            "Nán Hǎi",
            "Tiān Biàn",
            "Jiǔ Qí",
            "Rì",
            "Ran",
            "Dài yī",
            "Asellus Secundus",
            "Alkalurops",
            "Shàng Bì",
            "Jī Shī",
            "Menkib",
            "Shù Zǐ",
            "Komondor",
            "Yù Nǚ",
            "Jī Xīn",
            "Mira",
            "Tarazed",
            "Nekkar",
            "Megrez",
            "Tiān Yuè",
            "Adhafera",
            "Sūn",
            "Lilii Borea",
            "Tiān Lǐ",
            "Wěi Xiù",
            "Maasym",
            "Tiān Chuán",
            "Bā Kuí",
            "Uruk",
            "Fáng Xiù",
            "Rén",
            "Wǔ Dì Zuò",
            "Zhào",
            "Biē",
            "Tiān Hùn",
            "Zuǒ Zhí Fǎ",
            "Míng Táng",
            "Dài",
            "Petra",
            "Tiān Chuáng",
            "Tú Sì",
            "Tiān Huáng",
            "Poerava",
            "Jìn",
            "Homam",
            "Saiph",
            "Tài Yáng Shǒu",
            "Yòu Qí",
            "Dilmun",
            "Chechia",
            "Caph",
            "Tiān Huáng Dà Dì",
            "Wouri",
            "Tài Zǐ",
            "Zubenelhakrabi",
            "Líng Tái",
            "Algedi",
            "Elnath",
            "Zhāng Xiù",
            "Sòng",
            "Garnet Star",
            "Arneb",
            "Atakoraka",
            "Rasalas",
            "Alya",
            "Tiān Láng",
            "Sī Wēi",
            "Dschubba",
            "Yě Jī",
            "Paikauhale",
            "Wèi Xiù",
            "Tiān Jiē",
            "Kāi Yáng",
            "Gài Wū",
            "Zhù",
            "Belel",
            "Kū",
            "Běi Luò Shī Mén",
            "Nashira",
            "Chē Fǔ",
            "Alphard",
            "Dōng Shàng Xiàng",
            "Shì Xiù",
            "Felis",
            "Ayeyarwady",
            "Shǔi Wèi",
            "Shǎo Zǎi",
            "Praecipua",
            "Alhena",
            "Ukdah",
            "Mouhoun",
            "Menkalinan",
            "Jiǔ Hé",
            "Uklun",
            "Matar",
            "Nihal",
            "Tiān Yǔ",
            "Lerna",
            "Sī Guài",
            "Běi Dǒu",
            "Dōng Cì Xiàng",
            "Fá",
            "Liè Sì",
            "Yān",
            "Tiān Ē",
            "Yún Yǔ",
            "Hòu",
            "Zuó Gēng",
            "Jūn Nán Mén",
            "Dī Xiù",
            "Guī",
            "Zǐ Wēi Zuǒ Yuán",
            "Fén Mù",
            "Zhěn Xiù",
            "Xià Tái yī",
            "Zhōng Shān",
            "Rosalíadecastro",
            "Liesma",
            "Sualocin",
            "Hatysa",
            "Aldhanab",
            "Alruba",
            "Miaplacidus",
            "Shì",
            "Yòu Gēng",
            "Mago",
            "Zuǒ Shè Tí",
            "Wǔ Dì Nèi Zuò",
            "Tania Borealis",
            "Dà Líng",
            "Kaveh",
            "Chara",
            "Lí Zhū",
            "Jiǔ Yóu",
            "Dì Zuò",
            "Xī Cì Xiàng",
            "Hù Guā",
            "Ogma",
            "Dingolay",
            "Nèi Chú",
            "Mimosa",
            "Aludra",
            "Zōng",
            "Heze",
            "Naledi",
            "Vega",
            "Rastaban",
            "Hú Shǐ",
            "Rasalhague",
            "Tianyi",
            "Chasoň",
            "Sì Dú",
            "Alniyat",
            "Fang",
            "Electra",
            "Ruchbah",
            "Muphrid",
            "Marsic",
            "Itonda",
            "Zavijava",
            "Regor",
            "Liù Jiǎ",
            "Markeb",
            "Ashlesha",
            "Tiān Jiù",
            "Zhōng Tái yī",
            "Pī Lì",
            "Shǎo Wèi",
            "Terebellum",
            "Bellatrix",
            "Kornephoros",
            "Meleph",
            "Sì Fǔ",
            "Sadalsuud",
            "Shòu",
            "Zhèn Chē",
            "Dalim",
            "Qì Fǔ",
            "Zōng Rén",
            "Sheliak",
            "Qí Zhèn Jiāng Jūn",
            "Izar",
            "Zǐ",
            "Ain",
            "Márohu",
            "Gumala",
            "Baten Kaitos",
            "Shama",
            "Sika",
            "Nyamien",
            "Pincoya",
            "Ebla",
            "Sarin",
            "Propus",
            "Meridiana",
            "Shì Lóu",
            "Jìn Xián",
            "Zhī Nǚ",
            "Rigil Kentaurus",
            "La Superba",
            "Alderamin",
            "Zaurak",
            "Diphda",
            "Noquisi",
            "Jiǔ Qīng",
            "Cebalrai",
            "Macondo",
            "Yì Xiù",
            "Capella",
            "Wattle",
            "Zuò Qí",
            "Inquill",
            "Amansinaya",
            "Lǎo Rén",
            "Hǔ Bēn",
            "Xī Zhòng",
            "Yú",
            "Sagarmatha",
            "Wài Píng",
            "Keid",
            "Zhang",
            "Qīng Qiū",
            "Mizar",
            "Tiān Jīn",
            "Achird",
            "Hunahpú",
            "Phoenicia",
            "Funi",
            "Láng Wèi",
            "Skat",
            "Tiān Xiàng",
            "Aspidiske",
            "Qí Guān",
            "Diadem",
            "Arkab Posterior",
            "Zhàng Rén",
            "Aladfar",
            "Segin",
            "Zǐ Wēi Yòu Yuán",
            "Thuban",
            "Deneb Algedi",
            "Giausar",
            "Jǐng Xiù",
            "Theemin",
            "Xamidimura",
            "Tǔ Gōng Lì",
            "Elgafar",
            "Wazn",
            "Jiàn Tái",
            "Jī Shǔi",
            "Tiān Cāng",
            "Castor",
            "Pleione",
            "Nervia",
            "Tegmine",
            "Kang",
            "Nóng Zhàng Rén",
            "Bó Dù",
            "Peacock",
            "Chalawan",
            "Guǐ Xiù",
            "Niúláng or Qiānniú",
            "Sheratan",
            "Yòu Zhí Fǎ",
            "Taygeta",
            "Cháng Chén",
            "Baekdu",
            "Asellus Australis",
            "Prima Hyadum",
            "Xī Xián",
            "Anadolu",
            "Jī Zú",
            "Sargas",
            "Xià Tái",
            "Chē Qí",
            "Xuange",
            "Fù Ěr",
            "Mirzam",
            "Guàn Suǒ",
            "Tianguan",
            "Polis",
            "Edasich",
            "Jiù",
            "Phecda",
            "Yù Jǐng",
            "Tangra",
            "Shēn Xiù",
            "Acrab",
            "Xū Xiù",
            "Aljanah",
            "Hoggar",
            "Khambalia",
            "Zibal",
            "Titawin",
            "Toliman",
            "Axólotl",
            "Luó Yàn",
            "Miram",
            "Shén Gōng",
            "Tislit",
            "Fú Kuāng",
            "Tiān Mén",
            "Kaewkosin",
            "Seginus",
            "Shào Chéng",
            "Alshat",
            "Azmidi",
            "Sadr",
            "Elkurud",
            "Moldoveanu",
            "Diya",
            "Zōng Zhèng",
            "Běi Hé",
            "Revati",
            "Parumleo",
            "Karaka",
            "Zosma",
            "Jiàn",
            "Dǒu Xiù",
            "Botein",
            "Zhōng Tái èr",
            "Torcular",
            "Jishui",
            "Dìwö",
            "Mintaka",
            "Xī Shǎng Xiāng",
            "Natasha",
            "Sadalmelik",
            "Tiān Jié",
            "Ainalrami",
            "Xī Shàng Xiàng",
            "Flegetonte",
            "Naos",
            "Dōng Xián",
            "Bā Gǔ",
            "Adhara",
            "Arcalís",
            "Fawaris",
            "Sāmaya",
            "Sī Lù",
            "Tiān Yuān",
            "Bài Guā",
            "Hassaleh",
            "Bubup",
            "Asterope",
            "Citalá",
            "Dōng Hǎi",
            "Emiw",
            "Zaniah",
            "Kochab",
            "Absolutno",
            "Algenib",
            "Mahsati",
            "Jiǎo Xiù",
            "Xiàng",
            "Alnitak",
            "Yildun",
            "Alpherg",
            "Wǔ Chē",
            "Tǔ Gōng",
            "Tài Zūn",
            "Meissa",
            "Altair",
            "Tania Australis",
            "Beid",
            "Tiān Gāng",
            "Tiān Yǐ",
            "Tiān Yuán",
            "Angetenar",
            "Dombay",
            "Nenque",
            "Rigel",
            "Dōng Ōu",
            "Uúba",
            "Alcor",
            "Kaus Borealis",
            "Lionrock",
            "Sān Gōng",
            "Menkent",
            "Alterf",
            "Xià Tái èr",
            "Buna",
            "Furud",
            "Jūn Shì",
            "Sabik",
            "Alkaphrah",
            "Xī Shàng Jiàng",
            "Albali",
            "Jabbah",
            "Betelgeuse",
            "Añañuca",
            "Gloas",
            "Tiān Gǒu",
            "Niǎn Dào",
            "Kraz",
            "Tài Yǐ",
            "Denebola",
            "Alula Australis",
            "Salm",
            "Maru",
            "Tejat",
            "Yòu Shè Tí",
            "Lí Yú",
            "Lesath",
            "Nusakan",
            "Almaaz",
            "Shào Zǎi",
            "Atik",
            "Menkar",
            "Kamuy",
            "Fù Yuè",
            "Mothallah",
            "Azelfafage",
            "Celaeno",
            "Cháng Shā",
            "Kuí Xiù",
            "Shàng Tái yī",
            "Kù Lóu",
            "Sadalbari",
            "Intan",
            "Shàng Zǎi",
            "Illyrian",
            "Procyon",
            "Sham",
            "Syrma",
            "Grumium",
            "Láng Jiāng",
            "Sterrennacht",
            "Adhil",
            "Fafnir",
            "Alioth",
            "Shàng Tái",
            "Xiāng",
            "Phact",
            "Guniibuu",
            "Mpingo",
            "Dōng Shǎng Jiāng",
            "Alcyone",
            "Kaffaljidhma",
            "Schedar",
            "Arcturus",
            "Alfirk",
            "Alrescha",
            "Nahn",
            "Kàng Xiù",
            "Eltanin",
            "Shaula",
            "Héng",
            "Enif",
            "Lì Shí",
            "Matza",
            "Bélénos",
            "Situla",
            "Alchiba",
            "Tiān Chán",
            "Nosaxa",
            "Maia",
            "Xū Liáng",
            "Secunda Hyadum",
            "Anser",
            "Altais",
            "Merope",
            "Kurhah",
            "Huá Gài",
            "Zembra",
            "Fulu",
            "Aldhibah",
            "Chaophraya",
            "Cocibolca",
            "Pipoltr",
            "Malmok",
            "Nembus",
            "Alsafi",
            "Hé Zhōng",
            "Yǔ Lín Jūn",
            "Shào Bì",
            "Muscida",
            "Taiyi",
            "Suhail",
            "Tojil",
            "Yáng Mén",
            "Gienah",
            "Jiǔ Kǎn",
            "Nikawiy",
            "Pollux",
            "Unukalhai",
            "Chamukuy",
            "Algorab",
            "Gakyid",
            "Gomeisa",
            "Cursa",
            "Qín èr",
            "Sī Mìng",
            "Alkaid",
            "Piautos",
            "Alphecca",
            "Tiān Shè",
            "Tiān Miào",
            "Dziban",
            "Hòu Gōng",
            "Azha",
            "Ancha",
            "Hamal",
            "Bibhā",
            "Taika",
            "Sansuna",
            "Běi Jí",
            "Achernar",
            "Sirius",
            "Dì",
            "Aldulfin",
            "Antares",
            "Brachium",
            "Polaris",
            "Tupi",
            "Polaris Australis",
            "Fomalhaut",
            "Sharjah",
            "Arkab Prior",
            "Danfeng",
            "Geminga",
            "Ascella",
            "Mirach",
            "Filetdor",
            "Timir",
            "Wasat",
            "Shǎng Zǎi",
            "Porrima",
            "Alkarab",
            "Batsũ̀",
            "Tài Wēi Zuǒ Yuán",
            "Asellus Tertius",
            "Násti",
            "Pipirima",
            "Cujam",
            "Kaus Australis",
            "Tuiren",
            "Xihe",
            "Muspelheim",
            "Alnasl",
            "Ankaa",
            "Hadar",
            "Biham",
            "Mahasim",
            "Yed Prior",
            "Thabit",
            "Alrakis"
    );
}
